version: '3.9'

services:
  # MongoDB service
  mongo_db: #service's name, can be any
    image: mongo:latest # specify which image we want to use (it will be retrieved from dockerhub)
    restart: always
    ports: 
      - 2717:27017 # host:container
    volumes: # to get persist datas when stopping the container and return to it
      - mongo_db_volumne:/data/db # mongo_db is the volume which is created later
  
  # Mongo Express
  mongo_express:
    image: mongo-express
    ports:
      - 8080:8080

  # Node API service
  camagru_app:
    build: . # . means look for the Dockerfile in the same folder with this docker-compose.yml. And we use build because we want to build from our own image, not the one online.
    ports:
      - 4000:3000 # local machine's port : docker's node_api port
    # env_file:
    #   - .env
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: camagru_db
      NAME: blabla
    depends_on:
      - mongo_db
      - mongo_express
volumes:
  mongo_db_volumne:
    name: db_in_local_machine
    driver: local
    driver_opts: 
      type: 'none'
      device: /Users/nhungnguyen/Documents/camagru_volume